name: citations

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
            fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        - name: Install setup tools
          run: sudo apt-get install python3-setuptools
        - name: Install wheel
          run: pip3 install wheel
        - name: Install dependencies
          run: pip3 install beautifulsoup4 bibtexparser
        - name: Run scholar
          run: python3 scholar.py
        - name: Commit files
          run: |
            git config --local user.email "shikhartuli98@gmail.com"
            git config --local user.name "Shikhar Tuli"
            git add -A
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto commit (Citations update using GitHub workflow)" -a
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
        - name: Install jekyll
          run: |
            sudo apt-get install ruby-full build-essential zlib1g-dev
            echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
            echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
            echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
            source ~/.bashrc
            sudo gem install jekyll bundler
            bundle install
        - name: Rebuild page
          run: |
            sudo chmod +x bin/deployCI
            sudo ./bin/deployCI
        - name: Commit files
          run: |
            sudo git config --local user.email "shikhartuli98@gmail.com"
            sudo git config --local user.name "Shikhar Tuli"
            sudo git add -fA
            sudo git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: false
            branch: gh-pages
